# Generated by Django 5.0.6 on 2024-06-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news_post',
            name='author',
            field=models.CharField(default='Неизвестный автор', max_length=50, verbose_name='Автор'),
        ),
    ]
